<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{53e436ba-9af9-4ca4-ad7b-a6b2399fa417}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

//	fbLogHandler : FB_LogHandler;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//fbLogHandler();

// Run the Diagnostics PRG
DIAGNOSTICS();

(* FEE devices*)
PRG_FEE ();







]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="3" Count="6" />
      <LineId Id="37" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="10" Count="5" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>